version: '3'

networks:
  internal:

volumes:
  postgres:

services:
  ### PostgreSQL Service ##################################
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=billing_system
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal
