name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests PHP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Coding standards
        run: vendor/bin/php-cs-fixer fix --diff --verbose --dry-run .

      - name: Static analysis
        run: vendor/bin/phpstan

      - name: Tests
        run: vendor/bin/phpunit --coverage-clover clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer require php-coveralls/php-coveralls -n -W
          vendor/bin/php-coveralls --coverage_clover=clover.xml -v
